Make the best use of the whitespace in the UI, and center everything in the page to get the users attention.
MLH-Fellowship/pod-3.1.3-portfolio pull request #45
Opened 2021-07-21 13:29 UTC by anandrajaram21

### Why This PR Adds Value

- This PR cuts down on the final bundle size by removing unused CSS classes and making use of utility bootstrap classes, thereby keeping a consistent design language
- Before this, there was a lot of whitespace which wasn't utilized well as mentioned in issue #38. With this, the content has been centred wherever possible and the page has been mobile friendly without the need for media queries by using bootstrap

### What This PR Adds
- This PR uses the bootstrap grid system to create and centre individual items on the page, so as to grab the users attention as soon as possible.
- The bio section has been made short and concise to keep the user moving throughout the page. The user can get to know more with the social media links that will be added as mentioned in issue #3 
- This PR fixes the issue of navbar links not working as mentioned in issue #42 by adding the required IDs to the HTML attributes. 

### Screenshot

![image](https://user-images.githubusercontent.com/48560219/126495509-c774127a-82d6-4dc5-8737-207198e8d74d.png)

### How This PR Could Be Improved
- Smooth scrolling could be enabled for a smoother transition.
- For particularly long pages, a "scroll to top" button could be added.

### Issue This PR Closes

This closes #38 #40 #42 

Please do provide some feedback on how the UI design could be improved :)

2021-07-21 14:39 UTC, louisefindlay23 requested changes
@anandrajaram21, wow. You've certainly done a lot of refactoring. Great work :) Looks much nicer with centered cards.

On smaller screens though, some of the single cards look very wide because there's not much info in them. Would be nice to have a media query to account for this (reduce the card width). See screenshot below.

![Portfolio Card Centering](https://p392.p3.n0.cdn.getcloudapp.com/items/2NuqNKvD/bfadb79d-df92-475b-aa3f-0663f363aab7.jpeg?v=be0173e7745f33a9368e18d519f4eca6)

2021-07-21 16:42 UTC, anandrajaram21 commented
Ah okay, will do. I'll open up a new issue and work on it. Thanks for telling me about it.

2021-07-21 18:04 UTC, louisefindlay23 commented on _includes/about.html
> +      {% for item in site.data.about%}
Would add a space after the t here

2021-07-21 18:47 UTC, anandrajaram21 commented on _includes/about.html
> +      {% for item in site.data.about%}
ah, will do that right now

2021-07-21 19:07 UTC, louisefindlay23 approved these changes
Tested the deploy review and it looks great, @anandrajaram21. Awesome job.

2021-07-22 00:52 UTC, dtemir commented
@anandrajaram21 looks great!

2021-07-22 03:16 UTC, robzwolf requested changes
Looks clean! Can you fix the merge conflicts and re-request review from me once that's done?

2021-07-22 07:03 UTC, robzwolf approved these changes

2021-07-22 07:04 UTC, robzwolf commented
Great job fixing those merge requests! I know it can be a bit tough 😅

2021-07-22 07:04 UTC, merged