Add social media links
MLH-Fellowship/pod-3.1.3-portfolio pull request #51
Opened 2021-07-21 17:47 UTC by Green-Ranger11

### Why This PR Adds Value

This PR lets others get in touch with you and network by adding social media links to the footer.

### What This PR Adds

- This PR adds social links for Linkedin, Github and Twitter
- This PR adds a footer.
- The social media links only need to be defined in the config file.
- > Note: if you make any changes to the config file whilst serving you need to stop and rebuild for effect to show.

### Screenshot

![sdf](https://user-images.githubusercontent.com/39209557/126534560-070d60d7-4ab8-42d3-95a8-139ecdd69724.PNG)

### How This PR Could Be Improved

- Add more social network options such as youtube.
- Could look a lot better.
- Does it make sense in the footer? How about in the top like [Robbie's?](https://www.robbie.dev/)

### Issue This PR Closes

This closes #`3`

2021-07-22 03:18 UTC, robzwolf requested changes
I like this a lot – and I think the social media icons look better at the bottom of the site than at the top.

There are merge conflicts – can you fix them and then re-request a review from me?

2021-07-22 03:57 UTC, Green-Ranger11 commented
Thanks Robbie, I've resolved the merge conflicts.

2021-07-22 11:58 UTC, Green-Ranger11 commented
Okey dokey, some new changes broke it for me so I've now resolved them.

2021-07-23 12:25 UTC, robzwolf approved these changes

2021-07-23 12:25 UTC, merged